### ISSUE TITLE
SSA/ASS support

### ISSUE THREAD

**Issue by 5k3105** [asticode/go-astisub#1]
Looking forward to support of this format for my video application (https://github.com/5k3105/Trans-View).

**Comment by asticode** [comment]
@5k3105 I know it's been a while and I apologize for that, but I've added support for SSA/ASS subtitles. I'm not an expert in those subtitle formats and I've found incoherences between available documentations therefore feel free to let me know if you find anything not working as expected , I'll try to correct them.

**Comment by 5k3105** [comment]
Awesome Thanks!
