### ISSUE TITLE
Support configurable X-TIMESTAMP-MAP in webvtt

### ISSUE THREAD

**Issue by nakkamarra** [asticode/go-astisub#111]
I'd like to be able to set an `X-TIMESTAMP-MAP` before writing to WebVTT. Maybe could store it on `Metadata` as a struct? i.e
```go
type TimestampMap struct {
    LocalTimestamp time.Duration
    PresentationTimestamp in64
}
```

**Comment by nakkamarra** [comment]
Actually, now that I look through [what the webvtt reader is doing](https://github.com/asticode/go-astisub/blob/master/webvtt.go#L265) and think about it, this could just be done by directly by calculating the offset and then manually applying it i.e `subtitles.Add(calculatedOffset)` 🤔

**Comment by nakkamarra** [comment]
Actually I believe this needs to be reworked either way. 

@anupcshan @asticode I don't believe we can always just apply the timeOffset from the `X-TIMESTAMP-MAP` like we are doing [here](https://github.com/asticode/go-astisub/pull/63/files#diff-61991c3e38e65a683d9553a855b3ff61f8bb29ed780cd61d2e8f19622b899b24R270-R272), because if we want to be able to support writing the `X-TIMESTAMP-MAP` or manually applying the offset defined by it like my comment above suggests, we would have to consider the case that the current `*Subtitles` have been parsed from a WebVTT and the correction has already been applied. In this scenario we will have cue times that have been shifted by the offset, plus a header or `Add(...)` call applying the same offset again resulting in 2x the offset.

**Comment by nakkamarra** [comment]
[Here](https://github.com/asticode/go-astisub/pull/112/files#diff-7b52b6599ec9e123da9db19f3cec56292f1c60ae28d75d5ee59613d60c17127dR135-R137)'s an example of the usage in a PR I've created, the usage still supports both cases I think, but in @anupcshan 's case where you want to write a WebVTT without the header and the time offset applied, you can do so with a call to `Add()`

**Comment by nakkamarra** [comment]
Sorry for the annoying bump @asticode @anupcshan but any thoughts on this issue / PR?

**Comment by asticode** [comment]
No worries, I have seen your PR but didn't have much time to review it. I'll try to do it next week 👍
