### ISSUE TITLE
SSA/ASS '\N' line break flag should be convert to '\n' when write to WebVTT

### ISSUE THREAD

**Issue by zzzhr1990** [asticode/go-astisub#113]
SSA/ASS '\N' for line break, however, WebVTT uses '\n'. 

```golang
		as, err := astisub.ReadFromSSA(sourceSSAFileReader)
		if err != nil {
			return err
		}
		err = as.WriteToWebVTT(destVTTFileReader)
...
```

![linebreak_webvtt](https://github.com/user-attachments/assets/897abb05-709c-4ce3-bb2c-65173220eb8b)

Here's astio vs. ffmpeg output
[vtt_astio_ffmpeg_compare.zip](https://github.com/user-attachments/files/17213634/vtt_astio_ffmpeg_compare.zip)

**Comment by asticode** [comment]
I've pushed a fix on `master`, could you confirm this is working as expected?

If so, let me know whether you need a tag 👍

**Comment by zzzhr1990** [comment]
> working

Thank you! seems work perfect

**Comment by lllllmaster-lulllll** [comment]
> > working
> 
> Thank you! seems work perfect

which tag dou you know? can you give me the branch or tag? thank you

**Comment by asticode** [comment]
Last tag should be OK: `v0.32.1` 👍

**Comment by lllllmaster-lulllll** [comment]
> Last tag should be OK: `v0.32.1` 👍

thanks for you reply, but I got ` - ` after transformation . it seems that player does not support to parse the blow vtt
`你那所谓的魔术师在哪 - Where in hell is your so-called magician?`

ass
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:01:34.35,0:01:36.56,Default,,0000,0000,0000,,你那所谓的魔术师在哪\N{\fntahoma\fs10\1c&H0080FF&}Where in hell is your so-called magician?{\r}
Dialogue: 0,0:01:36.56,0:01:38.29,Default,,0000,0000,0000,,他会来的 兰斯洛特\N{\fntahoma\fs10\1c&H0080FF&}He will be here, Lancelot.{\r}
Dialogue: 0,0:01:38.39,0:01:39.69,Default,,0000,0000,0000,,他发过誓的\N{\fntahoma\fs10\1c&H0080FF&}He swore it.{\r}

vtt
WEBVTT

1
00:01:34.350 --> 00:01:36.560
你那所谓的魔术师在哪 - Where in hell is your so-called magician?

2
00:01:36.560 --> 00:01:38.290
他会来的 兰斯洛特 - He will be here, Lancelot.

3
00:01:38.390 --> 00:01:39.690
他发过誓的 - He swore it.

4
00:01:45.570 --> 00:01:47.430
他们正准备发动第二次进攻 - They're preparing for a second wave.

**Comment by asticode** [comment]
When I run `$ astisub convert -i <input_ssa_path> -o <output_vtt_path>` I do get the proper output using the latest tag.

Input:
```
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:01:34.35,0:01:36.56,Default,,0000,0000,0000,,你那所谓的魔术师在哪\N{\fntahoma\fs10\1c&H0080FF&}Where in hell is your so-called magician?{\r}
Dialogue: 0,0:01:36.56,0:01:38.29,Default,,0000,0000,0000,,他会来的 兰斯洛特\N{\fntahoma\fs10\1c&H0080FF&}He will be here, Lancelot.{\r}
Dialogue: 0,0:01:38.39,0:01:39.69,Default,,0000,0000,0000,,他发过誓的\N{\fntahoma\fs10\1c&H0080FF&}He swore it.{\r}
```

Output:
```
WEBVTT

1
00:01:34.350 --> 00:01:36.560
你那所谓的魔术师在哪
Where in hell is your so-called magician? 

2
00:01:36.560 --> 00:01:38.290
他会来的 兰斯洛特
He will be here, Lancelot. 

3
00:01:38.390 --> 00:01:39.690
他发过誓的
He swore it. 
```

What are you using to convert the format?

**Comment by lllllmaster-lulllll** [comment]
i import your code
here is mycode, maybe, I should replace ' - ' with '\n' in `vttText` here
--> ``vttFile.WriteString(fmt.Sprintf("%s\n\n", vttText))``
am I right?😁
thans
```go
func convertASSToVTT(srtFilePath, vttFilePath string, encoding string) (err
error) {
err = ConvertFileToUTF8(srtFilePath, srtFilePath+".utf8", encoding)
if err != nil {
return fmt.Errorf("error converting file to UTF-8: %v", err)
}
defer os.Remove(srtFilePath + ".utf8")
// 清理 ASS 文件中的特殊字符和格式标签
processedContent, err := cleanASSFile(srtFilePath + ".utf8")
if err != nil {
return fmt.Errorf("无法清理 ASS 文件: %v", err)
}

// 将清理后的内容写回临时文件
tempFilePath := "temp_processed.ass"
err = os.WriteFile(tempFilePath, []byte(processedContent), 0644)
if err != nil {
return fmt.Errorf("无法写入临时文件: %v", err)
}
defer os.Remove(tempFilePath)

// 使用 astisub 解析清理后的 ASS 文件
subtitles, err := astisub.OpenFile(tempFilePath)
if err != nil {
return fmt.Errorf("无法读取清理后的 ASS 文件: %v", err)
}

// 打开目标 VTT 文件
vttFile, err := os.Create(vttFilePath)
if err != nil {
return fmt.Errorf("无法创建 VTT 文件: %v", err)
}
defer vttFile.Close()

// 写入 VTT 文件头部
vttFile.WriteString("WEBVTT\n\n")

// 遍历 ASS 字幕条目，写入 VTT 文件
for i, subtitle := range subtitles.Items {
start := subtitle.StartAt
end := subtitle.EndAt

// 将字幕时间从 astisub 格式转换为 VTT 格式
startVTT := formatTimeToVTT(start)
endVTT := formatTimeToVTT(end)

// 写入字幕条目编号、时间和文本内容
vttFile.WriteString(fmt.Sprintf("%d\n", i+1)) // 字幕编号从 1 开始
vttFile.WriteString(fmt.Sprintf("%s --> %s\n", startVTT, endVTT))

// 清理字幕文本中的特殊字符和格式标签
vttText := subtitle.String()

// 写入字幕文本并加上换行
vttFile.WriteString(fmt.Sprintf("%s\n\n", vttText))
}
```



Quentin Renard ***@***.***> 于2025年2月21日周五 18:38写道：

**Comment by asticode** [comment]
How about simply using:

```go
s, _ := astisub.OpenFile(assPath)
s.Write(vttPath)
```

?

**Comment by lllllmaster-lulllll** [comment]
> How about simply using:
> 
> s, _ := astisub.OpenFile(assPath)
> s.Write(vttPath)
> ?

let me show you below
and the vtt file is empty either.

![Image](https://github.com/user-attachments/assets/9af0138c-e06b-4ee4-b590-ee1ac05032bd)

**Comment by lllllmaster-lulllll** [comment]
> > How about simply using:
> > s, _ := astisub.OpenFile(assPath)
> > s.Write(vttPath)
> > ?
> 
> let me show you below and the vtt file is empty either.
> 
> ![Image](https://github.com/user-attachments/assets/9af0138c-e06b-4ee4-b590-ee1ac05032bd)

astisub could not parse the aas file because it encoded in UTF-16LE. And double-caption ass file has complex grammar, astisub can not parse similar file.

**Comment by asticode** [comment]
What about converting your file to UTF8 first before opening it in astisub?
