### ISSUE TITLE
proposal: Support no indentation option in func (Subtitles) WriteToTTML

### ISSUE THREAD

**Issue by min0625** [asticode/go-astisub#116]
## Background
I noticed that the `WriteToTTML` function always indents the output. This is not a problem in most cases, but in some cases, storage space is limited, you may not want indentation.

## Proposal
I propose that:
- New method `WriteToTTMLWithOptions` in `Subtitles`.
- New type `TTMLWriteOptions` for `WriteToTTMLWithOptions`.

Define the following:
```go
// WriteToTTMLWithOptions writes subtitles in .ttml format with options.
func (s Subtitles) WriteToTTMLWithOptions(o io.Writer, opts TTMLWriteOptions) (err error) {
    // ...

	// Marshal XML
	var e = xml.NewEncoder(o)

    // Indent
    if opts.Indent != nil {
        e.Indent("", *opts.Indent)
    } else {
        e.Indent("", "    ")
    }

    // ...
}

// TTMLWriteOptions represents TTML write options.
type TTMLWriteOptions struct {
    Indent *string // Default is 4 spaces.
}

```

**Comment by asticode** [comment]
Good idea! 👍 

However I'd rather not have an additional `WriteToTTMLWithOptions()` method but instead:

- rename `TTMLWriteOptions` into `WriteToTTMLOptions`
- make `Indent` a `string`
- add a `type WriteToTTMLOption func(o *WriteToTTMLOptions)`
- transform `WriteToTTML` into `WriteToTTML(o io.Writer, opts ...WriteToTTMLOption)`
- at the beginning of `WriteToTTML` do something like
```go
// Create write options
wo := &WriteToTTMLOptions{Indent: "    "}
for _, opt := range opts {
  opt(wo)
}
```
- add
```go
func WriteToTTMLWithIndentOption(indent string) WriteToTTMLOption {
  return func(o *WriteToTTMLOptions) {
    o.Indent = indent
  }
}
```

and use `WriteToTTML(r, WriteToTTMLWithIndentOption(""))` to remove indentation

**Comment by min0625** [comment]
LGTM. I will adjust the PR later.

**Comment by min0625** [comment]
Hi @asticode,

The [PR](https://github.com/asticode/go-astisub/pull/117) is ready for review. Thanks.
