### ISSUE TITLE
Modify the text of an item

### ISSUE THREAD

**Issue by Senpos** [asticode/go-astisub#13]
Hi,

Is there an easy way to modify the whole text content of an item in SRT file?

For example, I have a file with the following content:
```
1
00:00:00,480 --> 00:00:04,380
hello
 world!

2
00:00:04,513 --> 00:00:08,346
this is
 test
```

It is malformed. I want to replace `"\n "` (`\n` and a space right after it) with `"\n"` (just a `\n`), so the results could be this:
```
1
00:00:00,480 --> 00:00:04,380
hello
world!

2
00:00:04,513 --> 00:00:08,346
this is
test
```

I see, that each item is split into lines, so simple `replace` call won't work.

Any suggestions?
Thanks.

**Comment by asticode** [comment]
@Senpos I would recommend looping through items and simply using `strings.TrimSpace` which will remove spaces at the beginning and the end of your line. Would that fix your issue?

**Comment by Senpos** [comment]
@asticode 
Hi,

Thanks for the reply.

Am I doing it wrong?

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"path"
	"strings"

	"github.com/asticode/go-astisub"
)

func main() {
	inputFile := flag.String("input", "", "path to the srt file")
	flag.Parse()

	srt, err := astisub.OpenFile(*inputFile)
	if err != nil {
		log.Fatalf("could not open %s: %v", *inputFile, err)
	}

	for _, item := range srt.Items {
		for _, line := range item.Lines {
			for _, lineItem := range line.Items {
				lineItem.Text = strings.TrimPrefix(lineItem.Text, " ")
			}
		}
	}
	srt.Write("fixed_" + path.Base(*inputFile))
}
```

The actual lines after I write to the file do not change.
Am I supposed to build `Item` objects and not modify internal `Subtitles.Items.Lines.Items.Text` directly?

**Comment by asticode** [comment]
The problem is that `lineItem` is a variable only valid in its `for` loop. When you update its value, you only update the value of the variable, not the value of the slice item.

What you need to do is something along the lines of:

```go
for idxItem := range srt.Items {
		for idxLine := range srt.Items[idxItem].Lines {
			for idxLineItem := range srt.Items[idxItem].Lines[idxLine].Items {
				srt.Items[idxItem].Lines[idxLine].Items[idxLineItem].Text = strings.TrimPrefix(srt.Items[idxItem].Lines[idxLine].Items[idxLineItem].Text, " ")
			}
		}
	}
```

Let me know if that works.

**Comment by Senpos** [comment]
That's working, thank you. :)

I have to admit, it is not the prettiest construction I've ever observed, but at least it works.
