### ISSUE TITLE
Cheetah CAP Files?

### ISSUE THREAD

**Issue by davidkotas** [asticode/go-astisub#15]
Hello there-  I apologize if this is the wrong venue for a simple question.

Do you plan to support CAP files in this library in the near future?

Thanks.

**Comment by asticode** [comment]
@davidkotas this is the perfect venue :)

Can you provide a link to specs of CAP files as well as online examples if possible ? I'm not familiar with those type of subtitles.

**Comment by davidkotas** [comment]
Hey there- thanks for responding!

So, after some research, I can't find a spec for the CAP file format.  This post has some information, though:  https://forum.videohelp.com/threads/345979-How-to-convert-subtitle-file-into-CAP-format#post2160889

Also, there is a subtitle editing library written in C# that implements CAP file parsing:  https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/SubtitleFormats/CheetahCaption.cs

I apologize, this is the best I could do.  I don't know too much about subtitles.

**Comment by asticode** [comment]
No worries. Would you have a test file you can share here by any chance?

**Comment by davidkotas** [comment]
Unfortunately, all the CAP files in my possession are proprietary.

So, I think I've found a way out of this predicament.  Can I/we/you close this ticket for now?

You may not want to implement CAP files anyway- from my research, Cheetah International doesn't exist anymore as a company!

**Comment by asticode** [comment]
Haha no problem, I'll close this issue. Best of luck!
