### ISSUE TITLE
STL Parsing TTI-TF without start box (0xb) character

### ISSUE THREAD

**Issue by asnapper** [asticode/go-astisub#19]
Hello @asticode 
I'm currently troubleshooting issues with some STL files, that loose all their text when converting to any other format.

So far i tracked it down to the TTI-TF which, as far as i understand the teletext.go:parseTeletextRow function correctly, requires to contain a byte with a value of 0xB (Start Box control character according to EBU Spec 3264), before any text is decoded.

What at this point is unclear to me is if i'm looking at a bug in astisub or a faulty STL file. Do you maybe have any insight into this? I couldn't find anything in the STL spec that says a start box character is required.

Cheers
Matt

---
spec: https://tech.ebu.ch/docs/tech/tech3264.pdf
suspicious STL file: https://github.com/asnapper/go-astisub/raw/6fad4995b64ef6fd09b57e6882fd96604476122e/testdata/CHPD0608.stl

**Comment by asticode** [comment]
@asnapper first off I'm no `.stl` expert therefore I may be wrong.

The way I understand the spec, the `Display Standard Code` contained in the `GSI` block indicates whether the text is encoded using open subtitling or teletext. If it's encoded using teletext, the `start box` control code must be present (at least following the teletext specs). If not, there's no need for such control code.

Your file have a `Display Standard Code` set to `1` which is `Level1-Teletext`. Which means it should have `start box`control codes.

But, again, I may be wrong 😞
