### ISSUE TITLE
I couldn't manage to find "Item" components when reading SRT.

### ISSUE THREAD

**Issue by MerNat** [asticode/go-astisub#21]
I wanted to get the ID number of a specific item of an SRT file; but it brings nil.

Tried this code:
` s1, _ := astisub.OpenFile("example-in.srt")`

`fmt.Println(s1.Items[0].Region)`

**Comment by asticode** [comment]
@MerNat could you share your .srt file by any chance ? It would make the debugging process much easier

**Comment by MerNat** [comment]
> @MerNat could you share your .srt file by any chance ? It would make the debugging process much easier

I’ve taken the srt file from the testdata folder of the repository.

**Comment by asticode** [comment]
ok that makes sense then : `.srt`s don't have `regions`, which is what you're trying to print.

If you try `fmt.Printf("%+v\n", s1.Items[0])`, this will print the actual `Item`.

**Comment by MerNat** [comment]
Right! But if that's the case, how do I get the Index "1" in 

> 1
00:01:39 --> 00:01:41,04
(deep rumbling)

Is there a way I can get "1" from the struct "Items"?

**Comment by asticode** [comment]
Unfortunately right now this lib [doesn't process](https://github.com/asnapper/go-astisub/blob/master/srt.go#L46) the `.srt`/`.vtt` indexes.

I see 2 solutions for that:

- you make the assumption that if you're accessing `s1.Items[v]` then the index will be `v+1`. However this won't be always the case.
- you add an `Index` attribute to the [Item](https://github.com/asnapper/go-astisub/blob/master/subtitles.go#L111) struct and populate it [here](https://github.com/asnapper/go-astisub/blob/master/srt.go#L46) and [here](https://github.com/asnapper/go-astisub/blob/master/webvtt.go#L191). And then submit a PR if you feel like it 👍

**Comment by MerNat** [comment]
@asticode I've modified the parts where you've mentioned. can you give me access so that I may submit a PR?

**Comment by asticode** [comment]
You don't need a special access to submit a PR normally. Option should be available in Github.

**Comment by MerNat** [comment]
I was thinking to just do it from here. But I've submitted it now.
