### ISSUE TITLE
how to support vtt style

### ISSUE THREAD

**Issue by eager7** [asticode/go-astisub#41]
when use subtitles.ReadFromWebVTT, then style message will be losted.
```
STYLE
::cue {
color: #fff;
text-shadow: 0 1px #000, 1px 0 #000, -1px 0 #000, 0 -1px #000;
font-size: 15vw;
}
```

**Comment by asticode** [comment]
Unfortunately, right now webvtt style is [not yet supported](https://github.com/asticode/go-astisub/blob/master/webvtt.go#L200).

Feel free to submit a PR if you feel like adding the feature.

Cheers
