### ISSUE TITLE
Setting STLTimecodeStartOfProgramme to zero before decoding STL?

### ISSUE THREAD

**Issue by TobbeEdgeware** [asticode/go-astisub#49]
Thanks for a very nice and useful library!

I've run into STL files where STLTimecodeStartOfProgramme is set to 10 hours while the actual timestamps start at 0. As far as I've understood, this is a "safety mechanism" to avoid non-processed insertion of subtitles.

Since the offset is subtracted from the timestamp at line 255 in stl.go, I end up with large negative timestamps:

https://github.com/asticode/go-astisub/blob/8c108a572cf9c538fa7fe5a86f85f72e948a681d/stl.go#L255

Looping through all cues and adding 10hours to each of them should give the correct values back, but it would be much more efficient and more transparent to have an option to set `STLTimecodeStartOfProgramme = 0` in the call to ReadFromSTL, or have this done automatically if the timestamps are less than the `STLTimecodeStartOfProgramme`. 

It's not clear to me what is the best way to progress here, but in order to not break the interface, maybe some optional parameters like in 

https://github.com/edgeware/mp4ff/blob/bb9320744777dc97f18034c8aed45a9bcdbaa995/mp4/file.go#L121

could be a viable alternative?

**Comment by asticode** [comment]
I don't mind breaking the signature of `ReadFromSTL` and I would basically do the same thing as for [teletext](https://github.com/asticode/go-astisub/blob/master/teletext.go#L335), by adding a `STLOptions` struct containing an `IgnoreTimecodeStartOfProgramme` attribute

**Comment by TobbeEdgeware** [comment]
Unfortunately, PR #50  was incorrect since it is not `o.Metadata.STLTimecodeStartOfProgramme` that is subtracted from the timestamps, but `g.timecodeStartOfProgramme`. I'll try make a new PR which includes a test to verify that the new option is really working. Sorry about that.

**Comment by TobbeEdgeware** [comment]
@asticode Thanks for the quick merge and the new bug-fix release!
