### ISSUE TITLE
ssa code

### ISSUE THREAD

**Issue by eager7** [asticode/go-astisub#54]
when i read this line:
```
Dialogue: 0,0:00:36.38,0:00:38.84,DX,NTP,0,0,0,!Effect,Even solo players need to\Ntake this more seriously{\fscx300}-{\r}

```
the result is nil. I read code :
https://github.com/asticode/go-astisub/blob/master/ssa.go#L1068

and find this func not handle text before {\fscx300}.
is this a feature or bug ?

**Comment by asticode** [comment]
This is definitely a bug 😫

I've pushed a fix on master as well as in the `v0.17.0` tag.

Let me know whether this is better.

**Comment by eager7** [comment]
can i join this project?

**Comment by asticode** [comment]
What do you mean by `join the project`?

You can submit PRs if you feel like contributing.
