### ISSUE TITLE
Any methods to suppress these annoying log.Printf

### ISSUE THREAD

**Issue by caryyu** [asticode/go-astisub#59]
As there are some invalid formats that will be parsed and can't be read properly, I'd like to know if it is possible to avoid this annoying output from the code below:

https://github.com/asticode/go-astisub/blob/aa9412f0b84df2d576ccfa3d36ef3ac2148f0c88/ssa.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L178-L199

Plus: If there's a method that I can verify whether or not the format is correct before that, will make it even better

**Comment by asticode** [comment]
Right now this is not possible to do so.

But I'm welcoming PRs to make the proper changes: 
- add an `SSAOptions` struct with `OnUnknownSectionName func(name string)` and `OnInvalidLine func(line string)` fields
- add this struct to the `ReadFromSSA` func
- by default make the callback log information
