### ISSUE TITLE
Installation instructions do not work with Go 1.17

### ISSUE THREAD

**Issue by VasekPurchart** [asticode/go-astisub#62]
Hi, I have never worked with Go before (but needed to use this cool lib/tool), so I might be wrong, but I believe the installation instructions do not work with Go 1.17+.

From what I found it is related to https://go.dev/doc/go-get-install-deprecation . I have tried using `install` but then I got:

```
go install github.com/asticode/go-astisub@latest
go: downloading github.com/asticode/go-astisub v0.19.0
go: downloading github.com/asticode/go-astikit v0.20.0
go: downloading github.com/asticode/go-astits v1.8.0
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading golang.org/x/text v0.3.2
package github.com/asticode/go-astisub is not a main package
```

I have solved my issue by using 1.16, but it would probably be helpful to address this somehow (maybe at least mention the version).

Thnaks for the great lib/tool :)

**Comment by asticode** [comment]
Thanks for letting me know!

I've updated the readme: https://github.com/asticode/go-astisub#installation

Does it sound good ?

**Comment by VasekPurchart** [comment]
Yes, thank you 👍 , verified it works with the newest one as well.
