### ISSUE TITLE
Add support for linear correction

### ISSUE THREAD

**Issue by Jacalz** [asticode/go-astisub#64]
One common operation on subtitles is to apply a linear correction to fix various sync issues. This basically means that you change one time in the beginning and one in the end and it then recalculates all subtitles in between in a linear fashion.

An example of this could be the linear correction of https://subshifter.bitsnbites.eu/.

**Comment by asticode** [comment]
@Jacalz I've added linear correction to the project. You can either use it in your code with `s.ApplyLinearCorrection()` or with the CLI with `apply-linear-correction`. Check out the README for more info and let me know whether this works properly 👍

**Comment by Jacalz** [comment]
It seems to work as expected. Thanks a lot :)
