### ISSUE TITLE
not support .ass file?

### ISSUE THREAD

**Issue by rhettli** [asticode/go-astisub#68]
s1, err := astisub.OpenFile("Call.Me.by.Your.Name.2017.BluRay.ass")
	if err != nil {
		return nil, err
	}
// s1.items  is nil, why ,if subtitle file is .srt ,it works.

**Comment by rhettli** [comment]
[Call.Me.by.Your.Name.2017.BluRay.ass.txt](https://github.com/asticode/go-astisub/files/8813306/Call.Me.by.Your.Name.2017.BluRay.ass.txt)

i am sorry,just this ass file can not parse,i try others ok

**Comment by rhettli** [comment]
ass  two language trs like one,so i must write myself,but still thanks,.srt still works

**Comment by asticode** [comment]
I think the problem comes from the fact that the file is UTF16-LE encoded and `astisub` doesn't handle it well. If you encode your `ass` file in `utf8` it seems to be fine 🤔
