### ISSUE TITLE
Populate originalEpisodeTitle and originalProgramTitle for STL file convertion

### ISSUE THREAD

**Issue by Mattarn** [asticode/go-astisub#71]
Hello

I want convert an SRT to STL.
How update originalProgramTitle and originalEpisodeTitle ?

KG

**Comment by asticode** [comment]
You can update the [Subtitle's Metadata](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L316) attribute after opening your `srt`. For `originalProgramTitle` you'll need to use [Title](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L343) and for `originalEpisodeTitle` you'll need to use [STLOriginalEpisodeTitle](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L338) that I've just added 👍

**Comment by Mattarn** [comment]
Hi asticode !
Thanks for your quick intervention ! Nice :-)

Did all metadata in GSI block and TTI block can be updated like it too ?
I need edit many STL metadata !

GSI : ![image](https://user-images.githubusercontent.com/7905418/201895574-0c3f7c62-4bce-4302-b5a6-90ff20e94c6f.png)
![image](https://user-images.githubusercontent.com/7905418/201895884-e4c1417b-bda2-4f1a-8685-d71cfc3c2aac.png)

TTI : 
![image](https://user-images.githubusercontent.com/7905418/201895945-990a33c0-1269-4796-82d5-b5a1490b2e00.png)

**Comment by asticode** [comment]
For now, you can't... but I'd welcome a PR adding those changes. If you're up for it, you can get inspiration from [this commit](https://github.com/asticode/go-astisub/commit/357c58359c72fcabbabb93f8b81e18eeb9e522e2)

**Comment by Mattarn** [comment]
Thanks you, , i will check that.
