### ISSUE TITLE
TTML styling conversion

### ISSUE THREAD

**Issue by saintberry** [asticode/go-astisub#9]
Are there any plans to add features for converting the styling in TTML input to various output formats (I'm hoping for VTT)

**Comment by asticode** [comment]
Well I've prepared the code for that, but never found the time to implement it fully.

The first step would be this [todo](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L198) which consists of converting all the `TTML` string values into pointers to their correct types (like for `ssa` style attributes for instance).

The second step would be to implement the content of the `propagate` methods for each type of subtitle (the `ttml` one is [here](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L245)) which are called everytime style attributes are parsed. To do that, you'll need to check if one attribute is present (`!= nil`), and fill other subtitle type's style attribute accordingly. You can check [this example](https://github.com/asticode/go-astisub/blob/master/subtitles.go#L239) to understand the logic.

I won't have time to work on this, but I'd be happy to review a PR.

**Comment by saintberry** [comment]
Thanks for the detailed response. When I get sometime I'll try take a look and send over a PR.

**Comment by dlecorfec** [comment]
Hello, my use case would be close (converting EBU-STL to WebVTT while keeping colors). I still can't fully understand astisub's architecture. Any additional hints for this specific case? ;)

**Comment by dlecorfec** [comment]
Ah, it seemed easier than planned, see PR #12 (not sure if it's the _proper_ way, though ...)
