### ISSUE TITLE
Broken VTT styling in output (0.26.0 only)

### ISSUE THREAD

**Issue by kloon15** [asticode/go-astisub#94]
[2_Eng.zip](https://github.com/asticode/go-astisub/files/12921033/2_Eng.zip)

The simplified code:
```
var sub *astisub.Subtitles
if strings.HasSuffix(file.Name, ".srt") {
sub, err = astisub.ReadFromSRT(fd)
} else if strings.HasSuffix(file.Name, ".ass") || strings.HasSuffix(file.Name, ".ssa") {
sub, err = astisub.ReadFromSSA(fd)
}
var buf = &bytes.Buffer{}
sub.WriteToWebVTT(buf)
```

**Comment by asticode** [comment]
What is actually missing is parsing the html tags in `.srt` (and other formats as well) and writing them in `.vtt` (and other formats as well).

I won't have time to work on this anytime soon but I'm welcoming PRs. I can point towards the proper direction 👍

**Comment by kloon15** [comment]
> What is actually missing is parsing the html tags in `.srt` (and other formats as well) and writing them in `.vtt` (and other formats as well).
> 
> I won't have time to work on this anytime soon but I'm welcoming PRs. I can point towards the proper direction 👍

I see, well i have some javascript code that does srt to vtt with styles as a starting point, but im far from a go dev. How complicated would this be in go?

**Comment by asticode** [comment]
Regarding parsing html tags in `.srt` we'd have to:

- add a `parseTextSrt()` method similar to [parseTextWebVTT](https://github.com/asticode/go-astisub/blob/master/webvtt.go#L288)

Regarding writing htmk tags in `.srt` we'd have to:

- add a `(li LineItem) srtBytes() (c []byte)` method similar to [webVTTBytes](https://github.com/asticode/go-astisub/blob/master/webvtt.go#L512)
